### ISSUE TITLE
Add labels to "Create Project page" and write them to system card on "create project"

### ISSUE THREAD

**Issue by rubenrouwhof** [MinBZK/amt#147]
In this task, we will add new fields to the create project page form. In this extended form, users can also select the labels that we also have in the decision tree. To get these labels, users can use the ai-decisiontree form.
See Clickup doc: https://app.clickup.com/9015737202/v/dc/8cp2evj-1815/8cp2evj-2015

Notes: 
- [x] Add a new field to the System card 
   - in which we store
      - the labels selected by the user (https://app.clickup.com/9015737202/v/dc/8cp2evj-515/8cp2evj-2275) 
      - we should reserve space for:
         - the path through the decision tree, this path contain the numbers but also *include the labels encountered along the path*.
         - the version of the decision tree
  - we should choose a name for the field, options are:
     - a risk_opensource_role_impact_profile
     - ai_act_profile
     - algorithmframework_profile
     - aisystem_profile field
  - we merge the publication category into the appropriate label
- don't forget to also adjust the system card schema
- [ ] #202 -> Make a task in the task-registry from the decision tree (but don't get the labels from there, get the labels from ai-act-decisiontree) RIGHT NOW WE WILL HARDCODE THIS 
- [ ]  Get requests from elsewhere are done in the following task #168
- [ ]  We translate labels in the following task #166
- [ ]  Embedding of the decision tree is done in the following task: #165
